// 智享/frontend/src/pages/Register.vue
<template>
  <!-- ...existing code... -->
  <div>
    <input v-model="phoneNumber" placeholder="请输入手机号" />
    <button @click="sendVerificationCode">发送验证码</button>
  </div>
  <!-- ...existing code... -->
</template>

<script>
export default {
  data() {
    return {
      phoneNumber: '',
      // ...existing code...
    };
  },
  methods: {
    // ...existing code...
    async sendVerificationCode() {
      try {
        const response = await this.$http.post('/api/send-verification-code', {
          phoneNumber: this.phoneNumber,
        });
        if (response.data.success) {
          this.$toast.success('验证码发送成功');
        } else {
          this.$toast.error('验证码发送失败');
        }
      } catch (error) {
        this.$toast.error('网络错误，请稍后重试');
      }
    },
  },
};
</script>

// 智享/frontend/src/pages/Register.jsx
import React, { useState, useEffect } from 'react';
import { sendVerificationCode, registerUser } from '../api/index';
import { toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

toast.configure();

const Register = () => {
  const [phoneNumber, setPhoneNumber] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [name, setName] = useState('');
  const [timer, setTimer] = useState(0);

  useEffect(() => {
    let interval;
    if (timer > 0) {
      interval = setInterval(() => {
        setTimer((prevTimer) => prevTimer - 1);
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [timer]);

  const handleSendVerificationCode = async () => {
    try {
      const response = await sendVerificationCode(email);
      if (response.data.message) {
        toast.success('验证码发送成功，有效期5分钟');
        setTimer(60); // 设置计时器为60秒
      } else {
        toast.error('验证码发送失败');
      }
    } catch (error) {
      toast.error('网络错误，请稍后重试');
    }
  };

  const handleRegisterUser = async () => {
    try {
      const response = await registerUser(email, password, name);
      if (response.data.message) {
        toast.success('注册成功');
      } else {
        toast.error('注册失败');
      }
    } catch (error) {
      toast.error('网络错误，请稍后重试');
    }
  };

  return (
    <div>
      <input
        type="text"
        value={phoneNumber}
        onChange={(e) => setPhoneNumber(e.target.value)}
        placeholder="请输入手机号"
      />
      <button onClick={handleSendVerificationCode} disabled={timer > 0}>
        {timer > 0 ? `重新发送 (${timer}s)` : '发送验证码'}
      </button>

      <input
        type="email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="请输入邮箱"
      />
      <input
        type="password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        placeholder="请输入密码"
      />
      <input
        type="text"
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="请输入姓名"
      />
      <button onClick={handleRegisterUser}>注册</button>
    </div>
  );
};

export default Register;
